# Generated by Django 2.2.1 on 2019-10-04 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PR', 'Primitive'), ('AR', 'Array'), ('SR', 'String')], default=('PR', 'Primitive'), max_length=2)),
                ('description', models.TextField()),
                ('file_name', models.CharField(choices=[(0, 'AlgoZoo'), (1, 'requirements.txt'), (2, 'session1.vim'), (3, 'README.md'), (4, 'zoo'), (5, 'coderunner'), (6, 'static'), (7, 'manage.py'), (8, 'Procfile'), (9, '.git')], default=(0, 'AlgoZoo'), max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
