# Generated by Django 2.1.7 on 2019-10-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateField()),
                ('solved', models.BooleanField(default=False)),
                ('solved_time_minutes', models.IntegerField()),
                ('test', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to='coderunner.Test')),
            ],
            options={
                'ordering': ['attempt_date'],
            },
        ),
    ]
