# Generated by Django 2.1.7 on 2019-10-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0002_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='test',
            new_name='solution',
        ),
    ]
