# Generated by Django 2.2.1 on 2019-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0004_auto_20191004_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('PR', 'Primitive'), ('AR', 'Array'), ('SR', 'String'), ('LL', 'Linked Lists'), ('SQ', 'Stacks and Queues'), ('BT', 'Binary Trees'), ('HP', 'Heaps'), ('SC', 'Searching'), ('HT', 'Hash Tables'), ('ST', 'Sorting'), ('BS', 'Binary Search Trees'), ('RC', 'Recursion'), ('DY', 'Dynamic Programming'), ('GA', 'Greedy Algorithms'), ('GR', 'Graphs'), ('PC', 'Parallel Computing')], default=('PR', 'Primitive'), max_length=2),
        ),
    ]
